name: PHP

on:
  pull_request: { }
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  php-library:
    uses: equisoft-actions/php-workflows/.github/workflows/php-library.yml@v6
    with:
      checks: psalm,phpcs
      php-version: '8.1'
      extensions: pcov
    secrets:
      GPR_KEY: ${{ secrets.GPR_KEY }}

  php-library-php-8-3:
    uses: equisoft-actions/php-workflows/.github/workflows/php-library.yml@v6
    with:
      checks: psalm
      php-version: '8.3'
      extensions: pcov
    secrets:
      GPR_KEY: ${{ secrets.GPR_KEY }}
