name: PHP

on:
  pull_request: { }
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  php-library:
    uses: equisoft-actions/php-workflows/.github/workflows/php-library.yml@v3
    with:
      checks: psalm,phpcs
      php-version: '8.1'
      extensions: pcov
    secrets:
      GPR_KEY: ${{ secrets.GPR_KEY }}
