name: PHP

on:
  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  php-library:
    uses: equisoft-actions/php-workflows/.github/workflows/php-library.yml@v2
    with:
      checks: psalm
      php-version: '7.4'
      extensions: pcov
    secrets:
      GPR_KEY: ${{ secrets.GPR_KEY }}
  php-library-8-1:
    uses: equisoft-actions/php-workflows/.github/workflows/php-library.yml@v2
    with:
      checks: psalm,qodana
      php-version: '8.1'
      extensions: pcov
    secrets:
      GPR_KEY: ${{ secrets.GPR_KEY }}
