name: PHP

on:
  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  php-library:
    uses: equisoft-actions/php-workflows/.github/workflows/php-library.yml@v8
    secrets: inherit
    with:
      checks: psalm,phpcs
      php-version: '8.3'
      extensions: pcov
